clusters:
  hosts:
    yoda:
      ansible_user: horta
      ansible_group: stegle-group
      ansible_host: yoda-login
      remote_tmp: /scratch
      homebrew_temp:
        HOMEBREW_TEMP: /scratch
    ebi:
      ansible_user: horta
      ansible_group: stegle-group
      ansible_host: ebi-login
      homebrew_temp:
        NOOP: noop
test:
  hosts:
    localhost:
      ansible_user: horta
      ansible_group: stegle-group
      ansible_port: 32769
      ansible_ssh_pass: horta
      homebrew_temp:
