clusters:
  hosts:
    yoda:
      ansible_user: horta
      ansible_group: stegle-group
      ansible_host: yoda-login
    ebi:
      ansible_user: horta
      ansible_group: stegle-group
      ansible_host: ebi-login
