---
- hosts: clusters
  remote_user: horta
  tasks:
    - name: Ensure I have permission to write
      file:
        path: "{{ syspath }}"
        owner: horta
        group: stegle-group
        mode: 0755
    - name: Set bashrc
      template:
        src: sys-bashrc.j2
        dest: "{{ syspath }}/.bashrc{{ sysver }}"
        owner: horta
        group: stegle-group
        mode: 0555
    - name: Set bashrc.cfg
      template:
        src: sys-bashrc.cfg.j2
        dest: "{{ syspath }}/.bashrc{{ sysver }}.cfg"
        owner: horta
        group: stegle-group
        mode: 0555
