---
- name: Create syspath
  file:
    path: "{{ syspath }}"
    owner: horta
    group: stegle-group
    mode: 0755
    state: directory
- name: Create syspath/bin
  file:
    path: "{{ syspath }}/bin"
    owner: horta
    group: stegle-group
    mode: 0755
    state: directory
- name: Create syspath/bin/stegle
  template:
    src: stegle.j2
    dest: "{{ syspath }}/bin/stegle"
    owner: horta
    group: stegle-group
    mode: 0755
- name: Create bashrc
  template:
    src: sys-bashrc.j2
    dest: "{{ syspath }}/.bashrc{{ sysver }}"
    owner: horta
    group: stegle-group
    mode: 0755
- name: Create bashrc.cfg
  template:
    src: sys-bashrc.cfg.j2
    dest: "{{ syspath }}/.bashrc{{ sysver }}.cfg"
    owner: horta
    group: stegle-group
    mode: 0755
- name: Create ~/.bashrc
  template:
    src: user-bashrc.j2
    dest: ~/.bashrc
    owner: horta
    group: stegle-group
    mode: 0755
    backup: yes
- name: Copy plink
  copy:
    src: files/plink
    dest: "{{ syspath }}/bin/plink"
    owner: horta
    group: stegle-group
    mode: 0755
- name: Copy plink2
  copy:
    src: "files/plink2_{{ inventory_hostname }}"
    dest: "{{ syspath }}/bin/plink2"
    owner: horta
    group: stegle-group
    mode: 0755
- name: Download qctool
  get_url:
    url: "http://rest.s3for.me/{{ inventory_hostname }}-cluster/qctool"
    dest: "{{ syspath }}/bin/qctool"
    owner: horta
    group: stegle-group
    mode: 0755
- name: Copy transfer
  copy:
    src: files/transfer
    dest: "{{ syspath }}/bin/transfer"
    owner: horta
    group: stegle-group
    mode: 0755
