#!/bin/env bash

# write to output to tmpfile because of progress bar
tmpfile=$( mktemp -t transferXXX )
curl --progress-bar --upload-file $1 https://transfer.sh/$(basename $1) >> $tmpfile; echo $(cat $tmpfile); rm -f $tmpfile;
