---
anaconda_name: 'Anaconda{{anaconda_python_ver}}-{{anaconda_ver}}-Linux-x86_64'
anaconda_installer_sh: '{{anaconda_name}}.sh'
anaconda_installer_url: '{{anaconda_mirror}}/{{anaconda_installer_sh}}'
anaconda_checksum: '{{anaconda_checksums[anaconda_installer_sh]}}'

anaconda_install_dir: '{{anaconda_parent_dir}}/{{anaconda_name}}'

anaconda_conda_bin: '{{anaconda_link_dir}}/bin/conda'
